// <auto-generated />
namespace BankingKataMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AccountNumberChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccountNumberChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201711271829416_AccountNumberChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
